### ISSUE TITLE
LRM Typos and Mistakes

### ISSUE THREAD

**Issue by G-ram** [G-ram/HAWK#2]
Some point we need to fix them!

**Comment by jstnchng** [comment]
i got it

On Wed, Nov 4, 2015 at 8:30 AM, Graham notifications@github.com wrote:

> Some point we need to fix them!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/G-ram/HAWK/issues/2.

## 

Justin Chang
Columbia University, CC '17
917-923-7527
